import type { jsPDF as jsPDFType } from "jspdf"

export interface SchoolProfile {
    name: string
    address?: string
    phone?: string
    email?: string
}

export interface PDFOptions {
    title: string;
    subtitle?: string;
    filename: string;
    schoolProfile: SchoolProfile;
    margin?: number;
}

export const createStandardPDF = async (options: PDFOptions) => {
    const { default: jsPDF } = await import("jspdf")
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = options.margin || 20

    // 1. Add Header
    addSchoolHeader(doc, options.schoolProfile, margin, pageWidth)

    // 2. Add Title Section
    addDocumentTitle(doc, options.title, margin, pageWidth, options.subtitle)

    return { doc, pageWidth, margin }
}

export const addSchoolHeader = (doc: jsPDFType, profile: SchoolProfile, margin: number, pageWidth: number) => {
    // School Logo Placeholder (Box with initials)
    doc.setFillColor(5, 150, 105) // Emerald-600
    doc.rect(margin, margin, 15, 15, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.text("SN", margin + 7.5, margin + 9, { align: "center" })

    // School Name
    doc.setTextColor(15, 23, 42) // Slate-900
    doc.setFontSize(18)
    doc.setFont("helvetica", "bold")
    doc.text(profile?.name || "SCHOOL NEXUS", margin + 20, margin + 5)

    // School Address
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(100, 116, 139) // Slate-500
    doc.text(profile?.address || "Kampala, Uganda", margin + 20, margin + 10)

    // Contact Info
    doc.setFontSize(8)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(148, 163, 184) // Slate-400
    doc.text(`TEL: ${profile?.phone || ""}  |  EMAIL: ${profile?.email || ""}`, margin + 20, margin + 15)

    // Header Divider
    doc.setDrawColor(5, 150, 105)
    doc.setLineWidth(0.5)
    doc.line(margin, margin + 25, pageWidth - margin, margin + 25)
}

export const addDocumentTitle = (doc: jsPDFType, title: string, margin: number, pageWidth: number, subtitle?: string) => {
    const y = margin + 35
    doc.setTextColor(15, 23, 42) // Slate-900
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text(title.toUpperCase(), margin, y)

    if (subtitle) {
        doc.setFontSize(9)
        doc.setFont("helvetica", "normal")
        doc.setTextColor(100, 116, 139)
        doc.text(subtitle, margin, y + 5)
    }
}

export const addInfoBox = (doc: jsPDFType, label: string, value: string, x: number, y: number, width: number, height: number, variant: 'default' | 'emerald' = 'default') => {
    const isEmerald = variant === 'emerald'

    doc.setFillColor(isEmerald ? 236 : 248, isEmerald ? 253 : 250, isEmerald ? 245 : 252) // Emerald-50 or Slate-50
    doc.roundedRect(x, y, width, height, 3, 3, "F")

    doc.setTextColor(isEmerald ? 5 : 148, isEmerald ? 150 : 163, isEmerald ? 105 : 184) // Emerald-600 or Slate-400
    doc.setFontSize(8)
    doc.setFont("helvetica", "bold")
    doc.text(label.toUpperCase(), x + 5, y + 6)

    doc.setTextColor(isEmerald ? 5 : 15, isEmerald ? 150 : 23, isEmerald ? 105 : 42) // Emerald-600 or Slate-900
    doc.setFontSize(11)
    doc.text(value, x + 5, y + 14)
}

export const addStandardFooter = (doc: jsPDFType, profile: SchoolProfile, margin: number, pageWidth: number, slogan?: string) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15)

    doc.setTextColor(148, 163, 184)
    doc.setFontSize(8)
    doc.setFont("helvetica", "italic")
    const footerText = slogan || "Excellence through Education"
    doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: "center" })

    doc.setFont("helvetica", "normal")
    doc.text(`Generated by ${profile?.name || "School Nexus"} Management System`, pageWidth / 2, pageHeight - 5, { align: "center" })
}

export const standardTableStyles = {
    theme: 'grid' as const,
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [5, 150, 105] as [number, number, number], textColor: 255, fontStyle: 'bold' as const },
    alternateRowStyles: { fillColor: [248, 250, 252] as [number, number, number] }
}
