name = "schoolnexuspro"
main = ".open-next/worker.js"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_PLATFORM = "cloudflare"
NODE_VERSION = "22"
NEXTAUTH_URL="https://schoolnexuspro.pages.dev"
NEXT_PUBLIC_SITE_URL = "https://schoolnexuspro.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "school-nexus-db"
database_id = "0c7e2517-ca46-4bd7-99a7-421ced6c1b70"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "school-nexus-assets"

[dev]
port = 3000
